# config.yaml
server:
  port: "8089"
  timeout: 10s

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "auth_api"
  sslmode: "disable"

jwt:
  secretKey: "your-secret-key-change-this-in-production"
  issuer: "auth-api"
  tokenDuration: 24h