version: '3.8'

services:
  # ฐานข้อมูล PostgreSQL สำหรับการทดสอบ
  postgres-test:
    image: postgres:15-alpine
    container_name: auth-api-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_api_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-test-network

  # บริการทดสอบ
  auth-api-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: auth-api-test
    depends_on:
      postgres-test:
        condition: service_healthy
    environment:
      - TEST_DB_HOST=postgres-test
      - TEST_DB_PORT=5432
      - TEST_DB_USER=postgres
      - TEST_DB_PASSWORD=postgres
      - TEST_DB_NAME=auth_api_test
    networks:
      - auth-test-network

networks:
  auth-test-network:
    name: auth-test-network
    driver: bridge